[package]
name = "proto_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0.12.1"
bytes = "1.5.0"

[build-dependencies]
prost-build = { version = "0.12.1" }